"""Make customer_id nullable in service_requests

Revision ID: 197250ca7516
Revises: 4211b8154054
Create Date: 2024-11-25 12:24:47.065652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197250ca7516'
down_revision = '4211b8154054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_requests', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
