"""Add contact_number and location fields to User model

Revision ID: 4211b8154054
Revises: c70987a83cea
Create Date: 2024-11-11 13:19:02.147677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4211b8154054'
down_revision = 'c70987a83cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pin_code', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('pin_code')
        batch_op.drop_column('location')
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
