"""Add resume_filename and approval_status to User model.

Revision ID: ec25cb651a9f
Revises: ee5747089397
Create Date: 2024-11-01 16:31:48.656152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec25cb651a9f'
down_revision = 'ee5747089397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('approval_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('approval_status')
        batch_op.drop_column('resume_filename')

    # ### end Alembic commands ###
